
services:
  db:
    image: mysql:8.0
    container_name: erp_db
    environment:
      MYSQL_DATABASE: erp_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: erp_backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: erp_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  db_data: